services:
#    glory_assets.twig.assetsextension:
    twig.extension.assets:
        class: Glory\Bundle\AssetsBundle\Twig\AssetsExtension
        arguments: [@service_container, @assets.packages, @twig.extension.httpfoundation]
        tag:
            - { name: twig.extension }
#    twig.extension.assets:
#        alias: glory_assets.twig.assetsextension